find $1/* -type f -print0 | xargs -0 sed -i '/^$/d'
find $1/* -type f -print0 | xargs -0 sed -i '/./!d' 
find $1/* -type f -print0 | xargs -0 sed -i '/[0-9],\|\.[0-9][0-9]*/!d'
find $1/* -type f -print0 | xargs -0 sed -i '/send_reply_time/d'
find $1/* -type f -print0 | xargs -0 sed -i 's/TIME.*:\s*//g' 
find $1/* -type f -print0 | xargs -0 sed -i 's/\./,/g'
find $1/* -type f -print0 | xargs -0 sed -i '/received unknown/d'
find $1/* -type f -print0 | xargs -0 sed -i '/decode_time/d'
find $1/* -type f -print0 | xargs -0 sed -i '/DUMP/d'
find $1/* -type f -print0 | xargs -0 sed -i '/File/d'
